#!/bin/bash

### LOGIN
POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json

{
  "email": "zizo@example.com",
  "password": "mypassword"
}
### SIGN UP
POST http://127.0.0.1:5000/api/auth/sign-up
Content-Type: application/json

{
  "email": "elgrandesimo53@gmail.com",
  "username": "mohammed",
  "password": "mypassword",
  "first_name": "Test",
  "last_name": "User",
  "age": 25,
  "sex": "male",
  "sexualPreference": "everyone",

  "title": "Engineer",
  "company": "ACME Corp",
  "industry": "Technology",
  "experienceLevel": "Mid-level",
  
  "education": "Bachelor's Degree",
  "bio": "I love coding!",
  "interests": ["Traveling", "Reading / Books", "Music", "Sports", "Cooking", "Movies"]
}


### GET-INTERSETS
GET http://127.0.0.1:5000/api/interests?category=Entertainment%20%26%20Media


Content-Type: application/json

###GET-INTERESTS-GROUPPED-CATEGORY
GET http://127.0.0.1:5000/api/interests/categories
Content-Type: application/json



### GET CURRENT USER
GET http://127.0.0.1:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOSwiZXhwIjoxNzY3OTcxNjg5fQ.Cmyvc1pfSTz3zT8YkRh161G48QZab7ySdingib2xPFU
Content-Type: application/json


### GET USER BY ID
GET http://127.0.0.1:5000/api/users/21
Content-Type: application/json


### UPDATE USER PROFILE
POST http://127.0.0.1:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMSwiZXhwIjoxNzY4MjE0NTExfQ.VDGeLAohpFqGNjJTqnGVevr6g86FKjuEPlJeyVfz9OA
Content-Type: application/json

{
  "bio": "Updated bio information.",
  "title": "Senior Engineer",
  "first_name": "UpdatedFirstName",
  "last_name": "UpdatedLastName"
}

### REQUEST PASSWORD RESET
POST http://127.0.0.1:5000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "elgrandesimo53@gmail.com"
}

### CONFIRM PASSWORD RESET
POST http://127.0.0.1:5000/api/auth/reset-password
Content-Type: application/json

{
  "token": "NqbYR_rmkR6Slr6vWmdsf2Re4XN-sLXQxnsYSJUF47s",
  "new_password": "23082002!"
}



### CONFIRM EMAIL
GET http://127.0.0.1:5000/api/auth/confirm-email?token=0yVwglot_yj9wkmgF2dR-uh6Cq1-r1m0W3qhfVMBCZU
Content-Type: application/json