"""still working

Revision ID: 4eac12bb5da0
Revises: 8fb97830bf1c
Create Date: 2026-01-09 14:17:32.736227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eac12bb5da0'
down_revision = '8fb97830bf1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image1', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('online')
        batch_op.drop_column('verified')
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
