"""password reset

Revision ID: e7c2e9cd2566
Revises: fdc07edc55a5
Create Date: 2026-01-12 13:13:43.808440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c2e9cd2566'
down_revision = 'fdc07edc55a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('reset_token_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('reset_token_hash',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
