"""create user

Revision ID: f2787321a172
Revises: ebab68d55771
Create Date: 2026-01-08 14:31:30.791044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2787321a172'
down_revision = 'ebab68d55771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('emailVerified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.Enum('male', 'female', 'n/o', name='sex'), nullable=True))
        batch_op.add_column(sa.Column('sexualPreference', sa.Enum('male', 'female', 'everyone', name='sexual_preference'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sexualPreference')
        batch_op.drop_column('sex')
        batch_op.drop_column('emailVerified')
        batch_op.drop_column('age')
        batch_op.drop_column('last_name')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
